### ISSUE TITLE
FS#453 - Patch: Fix get_uri() from freeing/allocating memory on each call.

### ISSUE THREAD

**Issue by Walther-MD** [conformal/xombrero#10]
While running xombrero-1.6.3 under valgrind, I became aware of the following "freed memory used" problem:

==28815== Invalid read of size 1
==28815== at 0x5B974E6: g_strdup (in /usr/lib/libglib-2.0.so.0.3400.3)
==28815== by 0x8066E80: notify_title_cb (xombrero.c:4325)
==28815== by 0x5B1019B: g_cclosure_marshal_VOID__PARAM (in /usr/lib/libgobject-2.0.so.0.3400.3)
==28815== by 0xCD9B7AF: ???
==28815== Address 0xc5abe48 is 0 bytes inside a block of size 16 free'd
==28815== at 0x402A367: free (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==28815== by 0x5B86484: ??? (in /usr/lib/libglib-2.0.so.0.3400.3)
==28815== by 0xCD9B7AF: ???

On inspection, the problem is that notify_title_cb() is invoking get_title() (which then invokes get_uri()) twice, and in the first case it returns "tmp_uri," which gets freed/allocated on the second call to this function. On further inspection, I realized that "get_uri()" is being invoked multiple times during execution, causing a waste of free/alloc calls which just rebuild the same string (when displaying non webkit pages).

This patch adds the function "set_xtp_meaning()" which takes care of setting up the tmp_uri variable as needed, thus resolving any memory problems when using the result of get_uri(). It also removes a fix elsewhere which was addressing the nature of get_uri, as it's no longer needed.

http://pastebin.com/whSGhkg9

**Comment by marcopeereboom** [comment]
I'll take this patch if you submit a PR.

**Comment by Walther-MD** [comment]
Sure, but... what's a PR? A Pull Request? I'll have to seek a little around Github documentation to see how I do that.

**Comment by marcopeereboom** [comment]
Yes a pull request.  I ask for that so that there is attribution and stuff.
