### ISSUE TITLE
Xombrero not finding flashplayer plugin

### ISSUE THREAD

**Issue by oonet** [conformal/xombrero#115]
Xombrero does not find installed flashplayer plugin.

Tried Xubuntu 15.04 and Xubuntu 15.10

Midori works with flashplugin as expected.

**Comment by marcopeereboom** [comment]
xombrero does not at all try to make flash work, kind of the opposite.

Flash must die, please help by not using it.

**Comment by oonet** [comment]
I too would like to see the end of flash, but many sites continue to use it. Customers are forced to use an alternate browser which is a nuisance. It does nothing to force sites to abandon flash.

Since flashplayer is a plugin, it would seem to make sense to be able to run it rather than switch browsers. Xombrero is great about letting people configure things that would make sense to no one else. Is there a way to enable flash for those strange awkward that need it?

**Comment by dajohi** [comment]
Flash isn't going to happen.  And as a customer, you have a choice.  For example, I have actually switched banks because losing bank required third-party cookies to be enabled to log in to my online banking portal.  If people stop installing flash, people will stop using flash.

**Comment by oonet** [comment]
I'm with you. If I don't seem to agree, it's because I can agree all too easily. It doesn't make us right.

When my customers try to access commercial sites running flash, I am pleased that xombrero alerts them to a problem. Unfortunately, a lot of non-commercial, non-profit sites run flash too. Not the fault of the organization. They paid a developer who, umpteen years ago, decided that flash was nifty keen. The organization is locked in. They don't have time or money to switch no matter how much they might want to.

The art of change is in the timing. Right now, people buy their computer from a box store and run flash right out of the box. Will flash stop running if you or I are unable to view a couple of flash based websites? I'd like to think so.

If it's hard to get flashplugin working in xombrero, then fine. It's not worth the bother. But if it's easy, why be stuck with a handicap that can be avoided?

Xombrero running flash might be in a position to discourage flash better than xombrero unable to run flash. Protesting what you can't have is too much like sour grapes. It makes flash seem like an advanced feature only the best software can run.

**Comment by marcopeereboom** [comment]
Flash is dead, has been dead and will not be resurrected.

Only flash use left is porn.

The point of xombrero is to help users remain somewhat private and prevent bad things from running (JS, flash etc).

If that doesn’t work for you then xombrero is not for you.  It actively breaks the web and certainly isn’t for everyone.  It is geared towards the practical paranoid.

**Comment by nicolasdanelon** [comment]
> Flash is dead, has been dead and will not be resurrected. **Only flash use left is porn.** The point of xombrero is to help users remain somewhat private and prevent bad things from running (JS, flash etc). If that doesn’t work for you then xombrero is not for you. It actively breaks the web and certainly isn’t for everyone. It is geared towards the practical paranoid.
true story, flash is dead jim

**Comment by oonet** [comment]
Only flash use left is porn? Off the top of my head, I can think of a couple of streaming services used by a host of public and commercial stations such as Comedy Central cc.com - livestream.com and mtvnservices.com. I am aware of more.

I'm not disagreeing with you that flash is going away. Ookla speed tests (such as speedtest.net) used flash but their new beta doesn't. It's just a matter of time. (Regardless of whether xombrero runs flash or doesn't.)

I also agree with you that xombrero should not run flash by default. My point is simply that if the flashplugin can be made to run without much effort, xombrero might be a better package for allowing it.

On the other hand, you make a good point that flash is a nuisance. More of a nuisance for me because I have to run Midori alongside Xombrero rather than Xombrero alone, but Midori also has its strengths. (It runs flash, strips regex text strings, etc.) If running flash would be difficult for Xombrero, it makes sense to save the effort and keep the package light.

**Comment by dajohi** [comment]
It is not about easy or difficult.  It is about principle.  As a browser that aims to protect privacy and try to be as secure as possible, why would supporting flash ever fit into the core principle?   You say flash is the nuisance, so why bark up xombrero's tree?  Go bark at cc.com, livestream.com, and mtvnservices.com and tell them to use html5 instead.

**Comment by oonet** [comment]
If security is core principle, I agree that flash doesn't fit well with it. Which is where easy or difficult comes in. Because another principle of xombrero seems to be choice. If it's easy to provide a choice, why not provide it? Advise against using it, by all means. But start from a position of strength.

The reviews of xombrero talk about it being a good choice for old systems that are too slow, small and weak to run a "modern," mainstream browser. They comment vaguely that xombrero has problems - it "takes minimalism too far." They prefer a "modern" browser whenever possible, and xombrero when not.

People believe this nonsense. So if xombrero is unable to run what you are advising *shouldn't* be run, the perception may be that xombrero is inadequate. Not that flash should be avoided.

You are right that I say flash is the nuisance, not xombrero. I have no problem not running flash and if xombrero was able to run flash, I would prefer to leave the feature disabled by default. I hope I'm not "barking" up xombrero's tree about this or anything else. It's just that if opposing flash is a matter of principle, as you say, what is the best way to go about it?

**Comment by dajohi** [comment]
I have lost all interest in this discussion; this is my last comment on this issue.

Don't use flash.  If you require it, use a different browser.

**Comment by oonet** [comment]
No worries :-)

**Comment by oonet** [comment]
Quick note . . . can't see http://forecast.io . . . useful site . . . no pornography :-)
