### ISSUE TITLE
sound on duolingo.com

### ISSUE THREAD

**Issue by mvhulten** [conformal/xombrero#116]
On some of the Duolingo courses sound does not work.  Apparently the questions using the proprietary _IVONA_ text-to-speech technology fail, as described by a Debian [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=802904).

I am using Xombrero 1.6.4 under OpenBSD 5.8.  Same problems.

**Comment by DaimyoKirby** [comment]
This problem still occurs, and running xombrero through the terminal didn't reveal anything particularly useful to me though.

Using Xombrero 1.6.4 in Arch Linux x86_64.

**Comment by marcopeereboom** [comment]
This falls in the webkit1 no longer does all the things bucket.
