### ISSUE TITLE
crash/memory issue with vertalen.nu

### ISSUE THREAD

**Issue by mvhulten** [conformal/xombrero#117]
When I go to http://www.vertalen.nu/, Xombrero usually crashes within ten seconds.
I get a "GSlice: failed to allocate 496 bytes". Detailed output [here](https://github.com/conformal/xombrero/files/44428/xombrero.txt).

I am running Xombrero 1.6.4 on OpenBSD 5.8.

**Comment by marcopeereboom** [comment]
Unfortunately that is a webkit issue.

**Comment by mvhulten** [comment]
Has a corresponding WebKit bug been reported?  I cannot find it.

Epiphany is using WebKit as well, and does not crash when www.vertalen.nu is loaded.

**Comment by marcopeereboom** [comment]
This is either a webkit or a gtk issue.
