### ISSUE TITLE
.xombrero.conf should override .xombrero/runtime

### ISSUE THREAD

**Issue by mvhulten** [conformal/xombrero#123]
At the first start of xombrero (without configuration) when using the search bar, it asks for the default search engine.  If selected, this is stored in the search_string variable in ~/.xombrero/runtime, a file that shows in the header it should not be editted.  When adding search_string to ~/.xombrero.conf, I expect this to override ~/.xombrero/runtime.  This does not happen, and the value in the latter file is used.

The man page does not state what has precedence; in my opinion that should be ~/.xombrero.conf, which could update files in the xombrero scratch directory if that is useful for the functioning of the program.

**Comment by marcopeereboom** [comment]
wrong way around.
