### ISSUE TITLE
focus on input fields

### ISSUE THREAD

**Issue by mvhulten** [conformal/xombrero#124]
When opening e.g. https://duckduckgo.com/ (via the address bar) the focus is initially on the DuckDuckGo search field as soon as it is visible.  As soon as the page is completely loaded, it loses focus (so no input but one is in the vi-like command mode).

I do not know if this is a bug in xombrero or of these websites, but it does not happen for Epiphany (it keeps focus on the search field).

Apropos, often when using the search field on github, it appears to have focus (blinking cursor) but it hasn't; it is then necessary to click a second time in the search field.

Using xombrero 1.6.4 on OpenBSD 5.8 STABLE.

**Comment by lhark** [comment]
I believe this is a feature, as you usually want to easily get the focus on the command bar. If you want to get the focus on the first field, just press the "i" key (vim insert mode).

**Comment by mvhulten** [comment]
Now I cannot reproduce the issue myself anymore, so I'm closing this report.

lhark, you're right, and this is the behaviour that is most useful. However, during the loading of at least some pages the focus is initially on an input field and looses focus after the page is fully loaded. While before I experienced that I lost the focus both while entering text and while doing nothing, now I only loose focus when I don't do anything while focus stays on the input field when typing text during page loading. Perfect, actually. I don't know why I appear to have had a different experience before.
