### ISSUE TITLE
Accept "Forwards" and "Backwards" events

### ISSUE THREAD

**Issue by mwburden** [conformal/xombrero#13]
Xombrero does not seem to do anything with "Forwards" and "Backwards" events sent by the OS.   The upshot of this is that the "Forwards" and "Backwards" buttons on my mouse don't do anything in Xombrero.

Is there a security reason for this (eg, making sure that a rogue program or device driver can't take over your browsing session?)

**Comment by marcopeereboom** [comment]
We'll take a patch if someone has one.
