### ISSUE TITLE
CenturyLink MyAccount page not working correctly

### ISSUE THREAD

**Issue by oonet** [conformal/xombrero#130]
No problem logging in, but several features appear broken. For instance, clicking Contact Us and the link to list all the contact information. A page comes up showing several buttons missing, including Technical Support Chat. Words say that the service is unavailable. On other browsers, there is a bright green button to start the chat session.

**Comment by marcopeereboom** [comment]
This is going to be webkit related and we don’t control that.

**Comment by oonet** [comment]
On Mon, 21 Mar 2016 16:34:22 -0700
Marco Peereboom <notifications@github.com> wrote:

> This is going to be webkit related and we don’t control that.

Works fine with Midori, also webkit based.

Not sure, but the buttons might require flash. I've found buttons for specific functions (not all buttons that look the same) malfunctioning on *many* sites because they depend on flash. It makes sense to have flash disabled by default (Midori doesn't do this but instead enables or disables flash for everything). Xombrero should disable flash but allow it to be enabled just for (important) pages that absolutely require it.

Daniel

-- 
Internet Central
1229 Cornwall Ave Ste 310
Bellingham, WA 98225-5023

Technical Support
support@oo.net
360-820-0900

http://oo.net

**Comment by marcopeereboom** [comment]
You don’t want to use flash.  If your bank uses flash it is time to move to a different bank.  No, really.

Your midori could have been linked to a different webkit or it is indeed flash.

**Comment by oonet** [comment]
On Tue, 22 Mar 2016 05:04:48 -0700Marco Peereboom <notifications@github.com> wrote:

> You don’t want to use flash.

I agree!

> If your bank uses flash it is time to move to a different bank.  No, really.

Actually, CenturyLink isn't my bank :-)

The problem with not having flash available is that it is integrated into a number of cdn's. Developers use the cdn's without knowing or caring that they depend on flash, and companies hire developers without knowing or caring what makes it all tick. This is a serious problem. It is also a fact of life. If we want to change it, we have to cut with the grain not go against it. Xombero should disable flash by default. Then there should be a way to enable flash when it's absolutely needed. This is how we show there's a problem without seeming incapable.
 
> Your midori could have been linked to a different webkit

Only one webkit installed.

Daniel

> or it is indeed flash.
> 
> > On Mar 21, 2016, at 9:01 PM, oonet <notifications@github.com> wrote:
> > 
> > On Mon, 21 Mar 2016 16:34:22 -0700
> > Marco Peereboom <notifications@github.com> wrote:
> > 
> > > This is going to be webkit related and we don’t control that.
> > 
> > Works fine with Midori, also webkit based.
> > 
> > Not sure, but the buttons might require flash. I've found buttons for specific functions (not all buttons that look the same) malfunctioning on *many* sites because they depend on flash. It makes sense to have flash disabled by default (Midori doesn't do this but instead enables or disables flash for everything). Xombrero should disable flash but allow it to be enabled just for (important) pages that absolutely require it.
> > 
> > Daniel
> > 
> > --
> > Internet Central
> > 1229 Cornwall Ave Ste 310
> > Bellingham, WA 98225-5023
> > 
> > Technical Support
> > support@oo.net
> > 360-820-0900
> > 
> > http://oo.net
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub <https://github.com/conformal/xombrero/issues/130#issuecomment-199583835>
> 
> 
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/conformal/xombrero/issues/130#issuecomment-199780995
-- 
Internet Central
1229 Cornwall Ave Ste 310
Bellingham, WA 98225-5023

Technical Support
support@oo.net
360-820-0900

http://oo.net

**Comment by marcopeereboom** [comment]
Not going to change my mind though.  flash should have been stillborn and somehow it is still trudging on as the living dead.

I am not going to compromise my web security for some pretty pictures.

**Comment by oonet** [comment]
On Tue, 22 Mar 2016 17:38:12 -0700
Marco Peereboom <notifications@github.com> wrote:

> Not going to change my mind though.

Please do not consider what I saying as an attempt to influence your decision one way or the other. If chatting about this results in your thinking of something new, that's great. That's what thinking is for. If I think of something new, that's good too. Too many critical sites are broken to xombrero. I need to find a way to get them working.

> flash should have been stillborn

That would be best!

> and somehow it is still trudging on as the living dead.

More living than dead, unfortunately. Because it's invisible, developers are integrating flash into their cdn's. Pages that run well in Firefox (etc) fail in xombrero. No one knows why. They assume it's a problem with xombrero. Buttons do nothing when you press them. Or meaningful data is replaced by "missing plugin." Or a page comes up blank or nothing happens while the cursor spins. This is on people's work sites (vpn's etc), online banking, medical portals, etc. Serious, indispensable tools that people cannot do without.

This problem I'm having on CenturyLink was hard to identify as flash. Because once the page loads okay using flash, it keeps working when I switch to xombrero. It appears that flash is used not to run the function but only to load it into the computer. Without flash, the function won't load and tech support appears to be offline.

> I am not going to compromise my web security 

I am in complete agreement with you here. Web security comes first. Flash should not be allowed to run . . . *unless* the user specifically enables it in a very narrow context. The strength of xombero is certainly security. It is also flexibility. Allowing users to determine their own needs and script their own solutions. There should be *some* solution to run flash scripts if you want the opportunity to discourage it. Otherwise, you are giving pro-flash installations like firefox an uncontested advantage.

>for some pretty pictures.

As you say, for pretty pictures, flash is mostly (though not completely) dead. Replaced and being replaced by html5. It's the cdn's that are the problem here. Do you see what I mean?

Daniel

> 
> > On Mar 22, 2016, at 1:50 PM, oonet <notifications@github.com> wrote:
> > 
> > On Tue, 22 Mar 2016 05:04:48 -0700Marco Peereboom <notifications@github.com> wrote:
> > 
> > > You don’t want to use flash.
> > 
> > I agree!
> > 
> > > If your bank uses flash it is time to move to a different bank. No, really.
> > 
> > Actually, CenturyLink isn't my bank :-)
> > 
> > The problem with not having flash available is that it is integrated into a number of cdn's. Developers use the cdn's without knowing or caring that they depend on flash, and companies hire developers without knowing or caring what makes it all tick. This is a serious problem. It is also a fact of life. If we want to change it, we have to cut with the grain not go against it. Xombero should disable flash by default. Then there should be a way to enable flash when it's absolutely needed. This is how we show there's a problem without seeming incapable.
> > 
> > > Your midori could have been linked to a different webkit
> > 
> > Only one webkit installed.
> > 
> > Daniel
> > 
> > > or it is indeed flash.
> > >
> > > > On Mar 21, 2016, at 9:01 PM, oonet <notifications@github.com> wrote:
> > > >
> > > > On Mon, 21 Mar 2016 16:34:22 -0700
> > > > Marco Peereboom <notifications@github.com> wrote:
> > > >
> > > > > This is going to be webkit related and we don’t control that.
> > > >
> > > > Works fine with Midori, also webkit based.
> > > >
> > > > Not sure, but the buttons might require flash. I've found buttons for specific functions (not all buttons that look the same) malfunctioning on *many* sites because they depend on flash. It makes sense to have flash disabled by default (Midori doesn't do this but instead enables or disables flash for everything). Xombrero should disable flash but allow it to be enabled just for (important) pages that absolutely require it.
> > > >
> > > > Daniel
> > > >
> > > > --
> > > > Internet Central
> > > > 1229 Cornwall Ave Ste 310
> > > > Bellingham, WA 98225-5023
> > > >
> > > > Technical Support
> > > > support@oo.net
> > > > 360-820-0900
> > > >
> > > > http://oo.net
> > > > —
> > > > You are receiving this because you commented.
> > > > Reply to this email directly or view it on GitHub <https://github.com/conformal/xombrero/issues/130#issuecomment-199583835>
> > >
> > >
> > >
> > > ---
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/conformal/xombrero/issues/130#issuecomment-199780995
> > --
> > Internet Central
> > 1229 Cornwall Ave Ste 310
> > Bellingham, WA 98225-5023
> > 
> > Technical Support
> > support@oo.net
> > 360-820-0900
> > 
> > http://oo.net
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > 
> 
> 
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/conformal/xombrero/issues/130#issuecomment-200095062
-- 
Internet Central
1229 Cornwall Ave Ste 310
Bellingham, WA 98225-5023

Technical Support
support@oo.net
360-820-0900

http://oo.net
