### ISSUE TITLE
Failed to Build on 64 bit openSUSE Linux

### ISSUE THREAD

**Issue by martinvahi** [conformal/xombrero#134]
ts2@linux-0fiz:~/m_local/bin_p/Xombrero/kompil/fff/xombrero$ ls
    about.c            freebsd              marco.c          torenabled.ico      xombrero.desktop
    ascii2txt.pl       hinting.js           netbsd           txt2tooltip.pl      xombrero.h
    autoscroll.js      history.c            osx              unix.c              xombreroicon1280.png
    buildver.sh        hsts-preload         playflash.sh     user-agent-headers  xombreroicon128.png
    completion.c       http-accept-headers  README.md        version.h           xombreroicon16.png
    config-checker.pl  inputfocus.c         release.sh       version.sh          xombreroicon256.png
    cookie.c           input-focus.js       settings.c       whitelist.c         xombreroicon32.png
    dragonfly          inspector.c          style.css        xombrero.1          xombreroicon48.png
    externaleditor.c   js-merge-helper.pl   tldlist.c        xombrero.c          xombreroicon64.png
    favicon.ico        linux                tld-rules        xombrero.conf       xombreroicon.png
    favorites          Makefile             tordisabled.ico  xombrero.css
    ts2@linux-0fiz:~/m_local/bin_p/Xombrero/kompil/fff/xombrero$ ./release.sh major
    [master 04e6f1d] Prepare for release 2.0.0.
     1 file changed, 3 insertions(+), 3 deletions(-)
    gpg: skipped "release@conformal.com": No secret key
    gpg: signing failed: No secret key
    error: gpg failed to sign the data
    error: unable to sign the tag
    release.sh: error: unable to create tag
    ts2@linux-0fiz:~/m_local/bin_p/Xombrero/kompil/fff/xombrero$ ./buildver.sh 
    XOMBRERO_1_6_4-6-g04e6f1dts2@linux-0fiz:~/m_local/bin_p/Xombrero/kompil/fff/xombrero$ ./config-checker.pl 
    Unrecognized switch: -P  (-h will show valid options).
    ts2@linux-0fiz:~/m_local/bin_p/Xombrero/kompil/fff/xombrero$ ./version.sh 
    2.0.0ts2@linux-0fiz:~/m_local/bin_p/Xombrero/kompil/fff/xombrero$ make
    Makefile:19: *** missing separator.  Stop.
    ts2@linux-0fiz:~/m_local/bin_p/Xombrero/kompil/fff/xombrero$ uname -a
    Linux linux-0fiz 3.16.7-35-desktop #1 SMP PREEMPT Sun Feb 7 17:32:21 UTC 2016 (832c776) x86_64 x86_64 x86_64 GNU/Linux
    ts2@linux-0fiz:~/m_local/bin_p/Xombrero/kompil/fff/xombrero$ date
    Thu Apr 28 23:55:45 EEST 2016
    ts2@linux-0fiz:~/m_local/bin_p/Xombrero/kompil/fff/xombrero$ gcc --version
    gcc (SUSE Linux) 4.8.3 20140627 [gcc-4_8-branch revision 212064]
    Copyright (C) 2013 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    ts2@linux-0fiz:~/m_local/bin_p/Xombrero/kompil/fff/xombrero$

The README.md-advertised key seems to be also offline. 
There's some version of it at [https://archive.is/i2bsE](https://archive.is/i2bsE)

**Comment by marcopeereboom** [comment]
release.sh is not meant to be used by 3rd parties.  Use make in the linux directory.

The script's purpose is to generate a signed tag on github.
