### ISSUE TITLE
hotkey conflict with some site, is it possible to disable the hotkeys on specific site?

### ISSUE THREAD

**Issue by dlintw** [conformal/xombrero#135]
Some site use javescript assign hotkey to navigating the site.(For example gmail).
That's caused the behavior stranger. Sometimes, I require to switch other browser to prevent this behavior.

I think it is better to support following commands:
set hotkey=off  # global disable
offsite save # let this site always disable hotkey(only support command setting)
offsite # show all hotkey off site listing
offsite save domain # www.peereboom.us will keep peereboom.us

**Comment by marcopeereboom** [comment]
use ctrl-z.

**Comment by dlintw** [comment]
This key is un-document on man page.
By the way, is this toggle or there is another key to undo this function?

**Comment by marcopeereboom** [comment]
ctrl-z gives you full keyboard passthrough.  I am confused as to why this isn't documented.  I swear I added it at some point.

The process is hit ctrl-z to have all keys go directly to website, then Esc to go back to normal mode.

**Comment by dlintw** [comment]
I just did "grep -r passthrough" in the full source. Only xombrero.conf and *.c file
I mean, it should appear in the man page.
