### ISSUE TITLE
for same youtube live channel, xombrero want flash plugin, but chromium don't require it.

### ISSUE THREAD

**Issue by dlintw** [conformal/xombrero#137]
I'm trying to view same youtube live channel.

xombrero notice me it can not play, it require upgrade flash plugin.

But chromium don't require it.(As I know, it have removed the flash function).

**Comment by tukoz** [comment]
Xombrero does not support security hasard such as Flash.

For html5 vidéos I have the "youtube-dl", "zenity" and "vlc" packages installed and I am using a keyboard shortcut, "Mod4-y", that runs the following script:
```
#!/bin/sh

xterm -e 'youtube-dl --no-part -f 18/0/h264-sd -o $HOME/video.vid `zenity --entry` & \
sleep 8 && vlc -f $HOME/video.vid vlc://quit; \
mv $HOME/video.vid $HOME/video.vid.old; \
pkill -n xterm & ksh'
```
To watch a YouTube video, I copy the URL to the clipboard, press "Mod4-y", paste the URL into the dialog, the video begins to download and after 8 seconds, vlc streams the video in fullscreen.

I've set up youtube-dl to download videos in medium quality for youtube, liveleak and vimeo ("18" selects medium quality for youtube, "0" for liveleak and "h264-sd" for vimeo). If you want to choose a better quality, run `youtube-dl -F URL` and replace `18/0/h264-sd` with your choices.

`youtube-dl --list-extractors` gives you a full list of supported sites.

There certainly are better ways to do this.

Also 
https://github.com/conformal/xombrero/blob/master/playflash.sh

**Comment by dlintw** [comment]
My major question is why chromium work and xombrero can not. I haven't install flash in chromium.(Or, how to I verify this?).  Because I want to use xombrero in a machine for novice user, too much linux operation is difficult for them.  It seems youtube detect xombrero don't support some format, So, it try to show flash for xombrero. I've tried fake a chromium useragent for youtube. But failed, too.

**Comment by tukoz** [comment]
yeah? above is the most effective waay I know of to watch vids from this cool low pro browser. I mean, browse with a browser, watch vids with a video player (and drops Flash ads), I can see the dev priorities and I share them. Not a newbie though.

**Comment by marcopeereboom** [comment]
Use youtube-dl.  Flash will never ever ever ever be integrated.

Final note: chromium has exactly 0 overlap with xombrero.
