### ISSUE TITLE
xombrero doesn't build under OSX

### ISSUE THREAD

**Issue by indexless** [conformal/xombrero#150]
At first, I had to replace webkit gtk version in the OSX Makefile:

```
$ git diff
 ...
-LIBS+= webkitgtk-3.0
+LIBS+= webkit2gtk-4.0
 ...
``` 
Then I ran 'make' in osx/ subdirectory, but it anyway failed with a lot of errors (see the [full log](https://github.com/conformal/xombrero/files/639386/make-log.txt)). Here is the C compiler version:

```
$ cc --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
Thank you in advance!

**Comment by marcopeereboom** [comment]
This is a known issue and unless someone sends a patch it won't be fixed.
