### ISSUE TITLE
FS#320 - 'save cert' + 'save new cert' -> infinite history of old certs

### ISSUE THREAD

**Issue by toddfries** [conformal/xombrero#2]
If one gets a cert warning and caches the new cert or if one issues ':cert save' one over-writes the local cert already stored. It would be awesome to preserve the old certs for various reasons not the least of which is to know when a mitm valid cert is used vs the original again.

Also, a farm of servers (encrypted.google.com anyone?) that changes certs frequently seems to suggest we could cache a pool of certs and accept them all as valid instead of annoyingly writing over the one previous one we've stored.

**Comment by marcopeereboom** [comment]
Yeah this is neat.  Patch please!
