### ISSUE TITLE
Frames are broken

### ISSUE THREAD

**Issue by ghost** [conformal/xombrero#22]
When I login to a site with frames, upon initial page load, frames are there. When I click on any link in one of the frames, only the page which is linked is opened, thus breaking the site/navigation.

I was able to test and reproduce it everytime in SquirrelMail and WHM, which I sometimes (unfortunately) must use.

Let me know if this is not reproducible for you and I can provide my `.xombrero.conf`.

**Comment by marcopeereboom** [comment]
that is a webkit issue.  xombrero does not control rendering.
