### ISSUE TITLE
"Entry point not found" error in USP10.dll when launching xombrero 1.6.3 on windows xp

### ISSUE THREAD

**Issue by sysfu** [conformal/xombrero#25]
Xombero 1.6.3 RC1 fails to launch on Windows XP with Entry Point Not Found error. There should be a FlySpray bug report about this same issue with much more detailed debugging info but I am unable to locate the old bug database.

Screenshot; 
![xombrero-launch-error](https://f.cloud.github.com/assets/829699/1641435/7e32aefa-5854-11e3-8714-700232ac8f0c.PNG)

**Comment by marcopeereboom** [comment]
Windows XP will not be supported by xombrero.  Hell, Windows XP isn't supported by microsoft.
