### ISSUE TITLE
Open Link in New Window using context menu doesn't work

### ISSUE THREAD

**Issue by nmeum** [conformal/xombrero#29]
If a site isn't allowed to execute javascript the "Open Link in New Window" option in the context menu doesn't work. However, opening the link in a new window using `hinting_newtab` does work, thus I assume that it is somehow possible to resolve this issue.

**Comment by marcopeereboom** [comment]
Yes it is possible to resolve.  xombrero does not override the context menu and therefore whatever is standard is what happens.  I'll take a patch for this.
