### ISSUE TITLE
FS#321 - cert per port not currently possible

### ISSUE THREAD

**Issue by toddfries** [conformal/xombrero#3]
https://example.com:443/
https://example.com:8443/

If it turns out that each use a different cert, and one wishes to be
notified when certs 'change', one will be notified the certs are
changing when infact they are not because they are not just tied to the
fqdn but also the port as well.

Saving the certs in such a way that ports can be identified and treated as a port of the unique fqdn would be highly desirable so only when a cert changed on a given port since the last cache of the cert from that port would users be notified.

**Comment by marcopeereboom** [comment]
I'll take a patch for this.
