### ISSUE TITLE
Setting only no_proxy triggers segfault

### ISSUE THREAD

**Issue by eradman** [conformal/xombrero#30]
I normally run with `http_proxy`, `http_proxy` and `no_proxy` set, but I noticed that if I only have `no_proxy` defined then xombrero crashes

    $ export no_proxy=localhost,127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12
    $ xombrero eradman.com
    Segmentation fault (core dumped)

    $ cat /etc/motd 
    OpenBSD 5.4-current (GENERIC.MP) #134: Tue Nov 12 15:27:28 MST 2013

So it seems that if I unset `http_proxy` I must also unset `no_proxy`

**Comment by marcopeereboom** [comment]
Is this still an issue?  I somewhat recall fixing this before.

**Comment by eradman** [comment]
Seems to be fixed now
