### ISSUE TITLE
Remove deprecated GTK usage.

### ISSUE THREAD

**Issue by jrick** [conformal/xombrero#32]
A user building xombrero on OS X has noticed a couple build warnings for calls to gtk_entry_set_inner_border.  This function has been deprecated since GTK 3.4 and needs to be removed.

For some reason, these warnings do not show up when building on my system (OpenBSD-current, GTK 3.10), nor have I seen them with any older OS or GTK versions.

**Comment by marcopeereboom** [comment]
We'll close these as we seem them.
