### ISSUE TITLE
Segmentation faults with inspector (and without)

### ISSUE THREAD

**Issue by fbreitwieser** [conformal/xombrero#34]
For some reason I get segmentation faults frequently on github.com. Reproducibly (ie every time) when I click 'Inspect Element' on certain font elements (eg Github Bootcamp): The inspection interface shows up, but shortly afterwards a segmentation fault occurs.  On archlinux.org, for example, this does not occur. gdb output of executable with debug table:
````
[New Thread 0x69a222f0 (LWP 2634)]
[Thread 0x69a222f0 (LWP 2634) exited]
Cannot access memory at address 0x1

Program received signal SIGSEGV, Segmentation fault.
Cannot access memory at address 0x1
0x6262db90 in ?? ()
````
Furthermore, while I was writing this issue using xombrero, it also failed with a segmentation fault at some point. 

Adding a minimal ````~/.xombero.conf```` file (e.g. just setting ````download_dir````) seems to remove the segmentation fault., I cannot show the backtrace of xombero compiled with debug flags, as it does not show there (````GTK_VERSION=gtk2 env CFLAGS=-DXT_DEBUG make```` and ````gdb ./xombrero````). I think the error does not show here again because of the config files, this time maybe because it does not find anything in ````/usr/local/share/xombrero```` (it complains on ````about:startpage````).

Using the newest xombrero from git, no custom configurations on ARM architecture with Arch Linux and XFCE.

**Comment by marcopeereboom** [comment]
These are well known webkit issues.  xombrero can not prevent these crashes.
