### ISSUE TITLE
Wrong text possitioning when open from the command line pointing to an anchor.

### ISSUE THREAD

**Issue by johnfound** [conformal/xombrero#36]
When opening a file with command line, where the file path contains local anchor ID, xombrero positions the text to the end, not where the anchor points.

      xombrero file://some_path/my_file.html#anchorID

After the window is opened (wrongly possitioned), focusing on the address bar and pressing ENTER make xombrero to posision the text as intended.

**Comment by marcopeereboom** [comment]
webkit issue that xombrero can not control.
