### ISSUE TITLE
Should the green bar when cert.pem is enabled be overridable by the theme?

### ISSUE THREAD

**Issue by kevlar700** [conformal/xombrero#37]
I enabled the cert.pem and found it refreshing from the usual EV rubbish.

I have since installed and modified a gtk3 theme which has prevented the colours in the url bar from showing on https sites.

Should I track down and fix this in the theme or can or should xombrero override it?

Thanks for a great browser.

**Comment by marcopeereboom** [comment]
I'll accept a patch but won't write the code.  CSS in GTK is deep deep voodoo that I do not understand.
