### ISSUE TITLE
Running xombrero for long period of time - did someone made tests?

### ISSUE THREAD

**Issue by johnfound** [conformal/xombrero#38]
I have some plans of using xombrero as a front-end of my application that have to run for very long period of times without restarting. It is industrial control application and uses server-push in order to display some information to its UI, implemented by HTML+JavaScript. 

Anyway, I tried with Firefox, but after a week of work it becomed so slow, that user interaction is impossible.

So, did someone have information about behavior of xombrero in similar uses?

**Comment by marcopeereboom** [comment]
I'd love to have the time to write a new go version of xombrero however the upstream components are not in place.  Once webkitgtk4 works we can reopen this debate.
