### ISSUE TITLE
html5 video broken

### ISSUE THREAD

**Issue by Link-Satonaka** [conformal/xombrero#39]
html5 video playback was working fine when I used xombrero built against gtk2. Then webkitgtk2 1.10.2 updated to webkitgtk2 2.2.5 on my system, and the html5 player a) looked different and b) doesn't work. I rebuilt xombrero against gtk3, and the html5 player looks like the new broken gtk2 interface, and also still doesn't work.

You can test playback with http://www.w3.org/2010/05/video/mediaevents.html

Not sure how relevant this is but one of the sites that I know worked before, escapistmagazine.com, produces this error in stdout
** Message: console message: http://www.escapistmagazine.com/videos/view/zero-punctuation/5558-Yakuza-Dead-Souls @0: XMLHttpRequest cannot load http://www.themis-media.com/videos/play/5558. Origin http://www.escapistmagazine.com is not allowed by Access-Control-Allow-Origin.

**Comment by marcopeereboom** [comment]
Embedded video is all handled by webkit or further upstream components that xombrero does not control.
