### ISSUE TITLE
Can't remove objects from runtime whitelist

### ISSUE THREAD

**Issue by Link-Satonaka** [conformal/xombrero#40]
Once something has been saved to the whitelist (eg with :cookie save domain) it doesn't seem to be possible to remove it, unless one exits xombrero and manually removes the line from ~/.xombrero/runtime

**Comment by marcopeereboom** [comment]
That is working as designed.  :cookie save domain means "we like this site's cookies forever and ever".  If you only want to allow cookies for a session don't save them.
