### ISSUE TITLE
FS#444 - user agent <-> site list

### ISSUE THREAD

**Issue by toddfries** [conformal/xombrero#5]
right now user agent is a global; it tracks that if there are multiple user agents it keeps the same one for a given website .. however there is no way to 'pin' a given user agent for a given website.

Some websites are stupid and behave way different based on the user agent, others couldn't care less and you are the judge if your browser works.

I'd rather have the default user agent for most sites, and have a list of exceptions so to speak.

Something akin to:
user_agent_site = *.stupidsite.com, Mozilla/5.0 (Windows; U; Windows NT 6.1; ru; rv:1.9.2.3) Gecko/20100401 Firefox/4.0 (.NET CLR 3.5.30729)
user_agent_site = *.stupid2site.com, Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_5; de-de) AppleWebKit/534.15+ (KHTML, like Gecko) Version/5.0.3 Safari/533.19.4
user_agent_site = *.stupid3site.com, Mozilla/5.0 (Windows; U; MSIE 9.0; WIndows NT 9.0; en-US))

**Comment by marcopeereboom** [comment]
I'll take a patch for this.
