### ISSUE TITLE
p and r keys don't work in input field

### ISSUE THREAD

**Issue by holtzermann17** [conformal/xombrero#51]
Hello: is there any reason why 'p' and 'r' wouldn't be inputting text in an input field?  I can use C-i to open an external editor and input these letters, but that's inconvenient.  These keys aren't mentioned at all in my keyboard conf.  All other letters work fine.

**Comment by marcopeereboom** [comment]
I'll close the issue since it isn't xombrero.

**Comment by holtzermann17** [comment]
:+1:
