### ISSUE TITLE
browsing github issues in xombrero causes crash ;-)

### ISSUE THREAD

**Issue by holtzermann17** [conformal/xombrero#52]
I went to https://github.com/conformal/xombrero/issues
and Xombrero crashed with this message:
`+  Trace/BPT trap: 5       xombrero`

I'm on Mac OS 10.9.2.  I tried to generate a stack trace with gdb but that didn't work, I can follow instructions if you provide them.

**Comment by marcopeereboom** [comment]
webkit issue.
