### ISSUE TITLE
segfault watching an embedded youtube video

### ISSUE THREAD

**Issue by installe** [conformal/xombrero#54]
If I remember correctly, the segfault occurred when I was watching an embedded youtube video, and then tried to click the youtube button to play it on the youtube site itself.

Stacktrace below. (I've since installed the debug symbols of libwebkitgtk, so if the same problem occurs again, I'll add a comment to this bug.)

#0  0x00007ffff3e378a2 in sweep_line_delete_edge (edge=0x7fffffff3888, sweep=0x7fffffff3520) at /tmp/buildd/cairo-1.12.16/src/cairo-bentley-ottmann-rectangular.c:558
#1  sweep_line_delete (rectangle=0x7fffffff3860, sweep=0x7fffffff3520) at /tmp/buildd/cairo-1.12.16/src/cairo-bentley-ottmann-rectangular.c:574
#2  _cairo_bentley_ottmann_tessellate_rectangular (rectangles=rectangles@entry=0x7fffffff36f0, num_rectangles=num_rectangles@entry=3, 
    fill_rule=fill_rule@entry=CAIRO_FILL_RULE_WINDING, do_traps=do_traps@entry=0, container=container@entry=0x7fffffff47f0)
    at /tmp/buildd/cairo-1.12.16/src/cairo-bentley-ottmann-rectangular.c:659
#3  0x00007ffff3e38193 in _cairo_bentley_ottmann_tessellate_boxes (in=in@entry=0x7fffffff4a40, fill_rule=fill_rule@entry=CAIRO_FILL_RULE_WINDING, 
    out=out@entry=0x7fffffff47f0) at /tmp/buildd/cairo-1.12.16/src/cairo-bentley-ottmann-rectangular.c:877
#4  0x00007ffff3e99e61 in fixup_unbounded (extents=extents@entry=0x7fffffff5bf0, boxes=boxes@entry=0x7fffffff5160, compositor=<optimized out>)
    at /tmp/buildd/cairo-1.12.16/src/cairo-traps-compositor.c:885
#5  0x00007ffff3e9b081 in composite_aligned_boxes (boxes=0x7fffffff5160, extents=0x7fffffff5bf0, compositor=0x7ffff4139ac0 <compositor.16213>)
    at /tmp/buildd/cairo-1.12.16/src/cairo-traps-compositor.c:1298
#6  clip_and_composite_boxes (compositor=compositor@entry=0x7ffff4139ac0 <compositor.16213>, extents=extents@entry=0x7fffffff5bf0, boxes=boxes@entry=0x7fffffff5160)
    at /tmp/buildd/cairo-1.12.16/src/cairo-traps-compositor.c:1774
#7  0x00007ffff3e9b433 in clip_and_composite_polygon (compositor=compositor@entry=0x7ffff4139ac0 <compositor.16213>, extents=extents@entry=0x7fffffff5bf0, 
    polygon=polygon@entry=0x7fffffff57d0, antialias=antialias@entry=CAIRO_ANTIALIAS_NONE, fill_rule=fill_rule@entry=CAIRO_FILL_RULE_WINDING, curvy=<optimized out>)
    at /tmp/buildd/cairo-1.12.16/src/cairo-traps-compositor.c:1562
#8  0x00007ffff3e9bb72 in _cairo_traps_compositor_fill (_compositor=0x7ffff4139ac0 <compositor.16213>, extents=0x7fffffff5bf0, path=0x1dbe3c8, 
    fill_rule=CAIRO_FILL_RULE_WINDING, tolerance=0.10000000000000001, antialias=CAIRO_ANTIALIAS_NONE) at /tmp/buildd/cairo-1.12.16/src/cairo-traps-compositor.c:2250
#9  0x00007ffff3e44ee7 in _cairo_compositor_fill (compositor=0x7ffff4139ac0 <compositor.16213>, surface=surface@entry=0x2078af0, op=op@entry=CAIRO_OPERATOR_IN, 
    source=source@entry=0x7ffff3efc8a0 <_cairo_pattern_white>, path=path@entry=0x1dbe3c8, fill_rule=fill_rule@entry=CAIRO_FILL_RULE_WINDING, 
    tolerance=0.10000000000000001, antialias=antialias@entry=CAIRO_ANTIALIAS_NONE, clip=clip@entry=0x3f804e0) at /tmp/buildd/cairo-1.12.16/src/cairo-compositor.c:203
#10 0x00007ffff3eb5a58 in _cairo_xlib_surface_fill (_surface=<optimized out>, op=CAIRO_OPERATOR_IN, source=0x7ffff3efc8a0 <_cairo_pattern_white>, path=0x1dbe3c8, 
    fill_rule=CAIRO_FILL_RULE_WINDING, tolerance=<optimized out>, antialias=CAIRO_ANTIALIAS_NONE, clip=0x3f804e0)
    at /tmp/buildd/cairo-1.12.16/src/cairo-xlib-surface.c:1646
#11 0x00007ffff3e88f14 in _cairo_surface_fill (surface=0x2078af0, op=CAIRO_OPERATOR_IN, source=0x7ffff3efc8a0 <_cairo_pattern_white>, path=0x1dbe3c8, 
    fill_rule=CAIRO_FILL_RULE_WINDING, tolerance=0.10000000000000001, antialias=CAIRO_ANTIALIAS_NONE, clip=0x3f804e0)
    at /tmp/buildd/cairo-1.12.16/src/cairo-surface.c:2255
#12 0x00007ffff3e4354f in _cairo_clip_combine_with_surface (clip=0x3f804e0, dst=dst@entry=0x2078af0, dst_x=<optimized out>, dst_y=<optimized out>)
    at /tmp/buildd/cairo-1.12.16/src/cairo-clip-surface.c:78
#13 0x00007ffff3e99b37 in create_composite_mask (compositor=compositor@entry=0x7ffff4139ac0 <compositor.16213>, dst=dst@entry=0x57100f0, 
    draw_closure=draw_closure@entry=0x7fffffff6f00, draw_func=<optimized out>, mask_func=mask_func@entry=0x0, extents=extents@entry=0x7fffffff7320)
    at /tmp/buildd/cairo-1.12.16/src/cairo-traps-compositor.c:500
#14 0x00007ffff3e9a761 in clip_and_composite_with_mask (src_y=0, src_x=0, src=0x376baf0, op=CAIRO_OPERATOR_OVER, draw_closure=0x7fffffff6f00, mask_func=0x0, 
    draw_func=<optimized out>, extents=0x7fffffff7320, compositor=0x7ffff4139ac0 <compositor.16213>) at /tmp/buildd/cairo-1.12.16/src/cairo-traps-compositor.c:546
#15 clip_and_composite (compositor=compositor@entry=0x7ffff4139ac0 <compositor.16213>, extents=extents@entry=0x7fffffff7320, 
    draw_func=draw_func@entry=0x7ffff3e98da0 <composite_boxes>, mask_func=mask_func@entry=0x0, draw_closure=draw_closure@entry=0x7fffffff6f00, need_clip=2)
    at /tmp/buildd/cairo-1.12.16/src/cairo-traps-compositor.c:1036
#16 0x00007ffff3e9ac11 in clip_and_composite_boxes (compositor=compositor@entry=0x7ffff4139ac0 <compositor.16213>, extents=extents@entry=0x7fffffff7320, 
    boxes=boxes@entry=0x7fffffff6f00) at /tmp/buildd/cairo-1.12.16/src/cairo-traps-compositor.c:1779
#17 0x00007ffff3e9bbd7 in _cairo_traps_compositor_fill (_compositor=0x7ffff4139ac0 <compositor.16213>, extents=0x7fffffff7320, path=0x4bcb278, 
    fill_rule=CAIRO_FILL_RULE_WINDING, tolerance=0.10000000000000001, antialias=CAIRO_ANTIALIAS_DEFAULT) at /tmp/buildd/cairo-1.12.16/src/cairo-traps-compositor.c:2219
#18 0x00007ffff3e44ee7 in _cairo_compositor_fill (compositor=0x7ffff4139ac0 <compositor.16213>, surface=surface@entry=0x57100f0, op=op@entry=CAIRO_OPERATOR_OVER, 
    source=source@entry=0x7fffffff7720, path=path@entry=0x4bcb278, fill_rule=fill_rule@entry=CAIRO_FILL_RULE_WINDING, tolerance=0.10000000000000001, 
    antialias=antialias@entry=CAIRO_ANTIALIAS_DEFAULT, clip=clip@entry=0x2078810) at /tmp/buildd/cairo-1.12.16/src/cairo-compositor.c:203
#19 0x00007ffff3eb5a58 in _cairo_xlib_surface_fill (_surface=<optimized out>, op=CAIRO_OPERATOR_OVER, source=0x7fffffff7720, path=0x4bcb278, 
    fill_rule=CAIRO_FILL_RULE_WINDING, tolerance=<optimized out>, antialias=CAIRO_ANTIALIAS_DEFAULT, clip=0x2078810)
    at /tmp/buildd/cairo-1.12.16/src/cairo-xlib-surface.c:1646
#20 0x00007ffff3e88f14 in _cairo_surface_fill (surface=0x57100f0, op=CAIRO_OPERATOR_OVER, source=0x7fffffff7720, path=0x4bcb278, fill_rule=CAIRO_FILL_RULE_WINDING, 
    tolerance=0.10000000000000001, antialias=CAIRO_ANTIALIAS_DEFAULT, clip=0x2078810) at /tmp/buildd/cairo-1.12.16/src/cairo-surface.c:2255
#21 0x00007ffff3e4c8ac in _cairo_gstate_fill (gstate=0x2129fd0, path=path@entry=0x4bcb278) at /tmp/buildd/cairo-1.12.16/src/cairo-gstate.c:1308
#22 0x00007ffff3e46499 in _cairo_default_context_fill (abstract_cr=0x4bcaf10) at /tmp/buildd/cairo-1.12.16/src/cairo-default-context.c:1058
#23 0x00007ffff3e3fd85 in cairo_fill (cr=0x4bcaf10) at /tmp/buildd/cairo-1.12.16/src/cairo.c:2201
#24 0x00007ffff6287d7d in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#25 0x00007ffff6939942 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#26 0x00007ffff693a4bb in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#27 0x00007ffff693abeb in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#28 0x00007ffff693cc35 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#29 0x00007ffff692f065 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#30 0x00007ffff68f569f in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#31 0x00007ffff68dead2 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#32 0x00007ffff698f362 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#33 0x00007ffff699b8bc in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#34 0x00007ffff699bb73 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#35 0x00007ffff699c2a0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#36 0x00007ffff699d13a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#37 0x00007ffff699b43a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#38 0x00007ffff699bb73 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#39 0x00007ffff699c2a0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#40 0x00007ffff699d13a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#41 0x00007ffff699b43a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#42 0x00007ffff699c1b0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#43 0x00007ffff699d13a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#44 0x00007ffff699b43a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#45 0x00007ffff699c1b0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#46 0x00007ffff699d13a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#47 0x00007ffff699b43a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#48 0x00007ffff699c1b0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#49 0x00007ffff699c39c in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#50 0x00007ffff687d695 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#51 0x00007ffff6e697e0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#52 0x00007ffff6a36233 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#53 0x00007ffff6a348e4 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#54 0x00007ffff68cde7d in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#55 0x00007ffff68d6038 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#56 0x00007ffff6a38f3c in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#57 0x00007ffff69b349d in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#58 0x00007ffff68e297d in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#59 0x00007ffff68f5703 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#60 0x00007ffff68dead2 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#61 0x00007ffff68e2ac3 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#62 0x00007ffff68e2c30 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#63 0x00007ffff68e2924 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#64 0x00007ffff68f5703 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#65 0x00007ffff68dead2 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#66 0x00007ffff68e2ac3 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#67 0x00007ffff68e2c30 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#68 0x00007ffff68e2924 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#69 0x00007ffff68f5703 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#70 0x00007ffff68dead2 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#71 0x00007ffff68e2ac3 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#72 0x00007ffff68e2c30 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#73 0x00007ffff68e2924 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#74 0x00007ffff68f5703 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#75 0x00007ffff68dead2 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#76 0x00007ffff68e2ac3 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#77 0x00007ffff68e2c30 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#78 0x00007ffff68e2924 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#79 0x00007ffff68f5703 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#80 0x00007ffff68dead2 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#81 0x00007ffff698a26c in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#82 0x00007ffff698f746 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#83 0x00007ffff699b918 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#84 0x00007ffff699c1b0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#85 0x00007ffff699d13a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#86 0x00007ffff699b43a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#87 0x00007ffff699c1b0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#88 0x00007ffff699c39c in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#89 0x00007ffff687d695 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#90 0x00007ffff6e697e0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#91 0x00007ffff6a36233 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#92 0x00007ffff6a348e4 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#93 0x00007ffff698a26c in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#94 0x00007ffff698f746 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#95 0x00007ffff699b918 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#96 0x00007ffff699c1b0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#97 0x00007ffff699d13a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#98 0x00007ffff699b43a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#99 0x00007ffff699c1b0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#100 0x00007ffff699d13a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#101 0x00007ffff699b43a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#102 0x00007ffff699c1b0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#103 0x00007ffff699d13a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#104 0x00007ffff699b43a in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
---Type <return> to continue, or q <return> to quit---[A
#105 0x00007ffff699c1b0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#106 0x00007ffff699c39c in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#107 0x00007ffff687d695 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#108 0x00007ffff6e697e0 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#109 0x00007ffff6190dc7 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#110 0x00007ffff62849c9 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#111 0x00007ffff6296862 in ?? () from /usr/lib/x86_64-linux-gnu/libwebkitgtk-3.0.so.0
#112 0x00007ffff32edf33 in g_timeout_dispatch (source=source@entry=0x212a2d0, callback=<optimized out>, user_data=<optimized out>)
    at /tmp/buildd/glib2.0-2.38.2/./glib/gmain.c:4451
#113 0x00007ffff32ed526 in g_main_dispatch (context=0x6945a0) at /tmp/buildd/glib2.0-2.38.2/./glib/gmain.c:3066
#114 g_main_context_dispatch (context=context@entry=0x6945a0) at /tmp/buildd/glib2.0-2.38.2/./glib/gmain.c:3642
#115 0x00007ffff32ed878 in g_main_context_iterate (context=0x6945a0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /tmp/buildd/glib2.0-2.38.2/./glib/gmain.c:3713
#116 0x00007ffff32edb3a in g_main_loop_run (loop=0xbb7be0) at /tmp/buildd/glib2.0-2.38.2/./glib/gmain.c:3907
#117 0x00007ffff58305a5 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#118 0x000000000040c114 in main (argc=0, argv=0x7fffffffe2d0) at ../xombrero.c:8891

**Comment by marcopeereboom** [comment]
Upstream issue outside of xombrero's control.
