### ISSUE TITLE
FS#328 - icon resize sanity

### ISSUE THREAD

**Issue by toddfries** [conformal/xombrero#6]
as seen with gtk3 icons are not autosized properly in GtkEntry dialogs

this diff: http://todd.fries.net/pub/iconsize.diff

attempts to correct the problem.

The icons indeed get resized properly based on the text height in
GtkEntry widgets, and the GtkImage item in the compact tabs gets sized
properly based on the label attributes.

Issues to resolve before committing the above diff:

- memleaks (I'm sure there are several)
- sanity checking my coding
- updating to current codebase (developed against an early gtk3 port)

Currently, the resize issue is limited to when fonts are not the default.  This
is visible in the url bar and the statusbar.  If I enable the statusbar and icons in the status bar and fonts at a size of 6 per below it cuts off the lower
1/3 of e.g. the github favicon circle as it does not resize the favicon to fit in the height of the statusbar.

statusbar_font          = monospace normal 6
enable_favicon_entry    = 1
enable_favicon_tabs     = 1
default_zoom_level      = 0.65
show_tabs               = 0
show_url                = 0
show_statusbar          = 1
statusbar_elems         = BpZT
icon_size               = 1

**Comment by marcopeereboom** [comment]
If this is still an issue please reopen.  I have reasons to believe this was fixed in GTK.
