### ISSUE TITLE
Reproducible segfault with configuration default_zoom_level = 0.75

### ISSUE THREAD

**Issue by kevlar700** [conformal/xombrero#60]
Xombrero with webkit 2.4.0 on an OpenBSD snapshot from Apr 8th as well as the last webkit version on an older snapshot reproducibly segfault every time for me when visiting the following url with the configuration option default_zoom_level = 0.75 even with an otherwise empty xombrero.conf.

http://www.openbsd.org/papers/lvee_2014_winter_ports

MiniBrowser seems unaffected but I am not sure if MiniBrowser/Webkit can be configured with a zoom level. I had an issue with uploads not being accepted by a site the other week with a terminal message each time:

(xombrero:31324): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service 

I have since put that service back but haven't tested the upload on that site yet and can't see any useful dconf settings so perhaps it was just after the file selection dialog size (file selection worked). I had a quick grep of the source but if any one knows off hand what webkit uses dconf for and if/how things like websockets can be turned off, I would be interested.

Also any knowledge on what the following databases are used for would save me the trouble of investigating further.

.local/share/webkit/databases/

Thanks

**Comment by marcopeereboom** [comment]
I need a trace of the crash.  Please reopen if you see it again with the backtrace.
