### ISSUE TITLE
Window focus behavior breaks autotypers

### ISSUE THREAD

**Issue by devlinzed** [conformal/xombrero#64]
My password manager uses xdotool to write keys to the browser, but moving your focus from xombrero leaves insert mode, making it impossible to write in password fields or the command line.

**Comment by marcopeereboom** [comment]
I feel your pain but at this time I am uncomfortable altering behavior that has existed forever in the browser.  Changing default behavior that was thought through at some point always makes me very cautious.  Don't forget that counter to your needs there are a lot of people who are used to it behaving as it does.
