### ISSUE TITLE
ewf.companieshouse.gov.uk ssl yellow even with valid pem file

### ISSUE THREAD

**Issue by kevlar700** [conformal/xombrero#65]
http://marc.info/?l=openbsd-misc&m=140137375431301&w=2

For some reason ewf.companieshouse.gov.uk gives a yellow bar even though openssl using the same pem file comes back with OK.

I haven't found any other site that does this so far.

Version: 1.6.3
WebKit: 2.4.3
User Agent: 538.15
WebKit API: 3.0

**Comment by marcopeereboom** [comment]
That means that the system wide white list of CAs is out of date.  Have your OS vendor update it.
