### ISSUE TITLE
Xombrero 1.6.3 error in usp10.dll at WinXP

### ISSUE THREAD

**Issue by ospyrosmas** [conformal/xombrero#67]
Windows XP SP3 english latest updates. Install xombrero just fine, but it doesn't run. The error is: The procedure entry point ScriptItemizeOpenType could not be located in the dynamic link library USP10.dll. Is it supposed, this browser is created to run on low end pc or is it created to be run on windows 7?

**Comment by marcopeereboom** [comment]
Windows XP is deprecated.  xombrero never worked on it and never will.  Consider updating your OS since the vendor has given up on it.
