### ISSUE TITLE
Segmentation fault with inspector open

### ISSUE THREAD

**Issue by skirge** [conformal/xombrero#68]
I was browsing delicious.com with Webkit Inspector window open.

Segmentation fault occured.

Version is xombreror 1.6.3 compiled with WITH_DEBUG=yes on FreeBSD 10.

Backtrace

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 811c06400 (LWP 101231/xombrero-bin)]

0x0000000000443b22 in notebook_switchpage_cb (nb=0x854dde090, nbp=0x85f82e260, pn=0x3, udata=0x0) at ../xombrero.c:7960
7960			if (t->tab_id == pn) {
Current language:  auto; currently minimal
gdb$ bt
#0  0x0000000000443b22 in notebook_switchpage_cb (nb=0x854dde090, nbp=0x85f82e260, pn=0x3, udata=0x0) at ../xombrero.c:7960
#1  0x0000000804e9e311 in g_closure_invoke () from /usr/local/lib/libgobject-2.0.so.0
#2  0x0000000804eb29aa in g_signal_emitv () from /usr/local/lib/libgobject-2.0.so.0
#3  0x0000000804eb3695 in g_signal_emit_valist () from /usr/local/lib/libgobject-2.0.so.0
#4  0x0000000804eb3d84 in g_signal_emit () from /usr/local/lib/libgobject-2.0.so.0
#5  0x000000080256b241 in gtk_notebook_set_action_widget () from /usr/local/lib/libgtk-3.so.0
#6  0x000000080253fb5b in _gtk_marshal_BOOLEAN__BOXEDv () from /usr/local/lib/libgtk-3.so.0
#7  0x0000000804e9e57a in _g_closure_invoke_va () from /usr/local/lib/libgobject-2.0.so.0
#8  0x0000000804eb3361 in g_signal_emit_valist () from /usr/local/lib/libgobject-2.0.so.0
#9  0x0000000804eb3d84 in g_signal_emit () from /usr/local/lib/libgobject-2.0.so.0
#10 0x00000008026742a3 in gtk_widget_event () from /usr/local/lib/libgtk-3.so.0
#11 0x000000080253f52c in gtk_get_current_event_device () from /usr/local/lib/libgtk-3.so.0
#12 0x000000080253eb1a in gtk_main_do_event () from /usr/local/lib/libgtk-3.so.0
#13 0x0000000802ad2007 in _gdk_x11_display_queue_events () from /usr/local/lib/libgdk-3.so.0
#14 0x000000080512d702 in g_main_context_dispatch () from /usr/local/lib/libglib-2.0.so.0
#15 0x000000080512daa3 in g_main_context_pending () from /usr/local/lib/libglib-2.0.so.0
#16 0x000000080512db34 in g_main_context_iteration () from /usr/local/lib/libglib-2.0.so.0
#17 0x00000008048cd68d in soup_session_send_request_finish () from /usr/local/lib/libsoup-2.4.so.1
#18 0x00000000004373b2 in show_ca_status (t=0x85c0b0600, uri=0x85fa679e0 "https://delicious.com/tools") at ../xombrero.c:3732
#19 0x0000000000438389 in notify_load_status_cb (wview=0x854d766c0, pspec=0x854cab920, t=0x85c0b0600) at ../xombrero.c:4224
#20 0x0000000804e9e311 in g_closure_invoke () from /usr/local/lib/libgobject-2.0.so.0
#21 0x0000000804eb29aa in g_signal_emitv () from /usr/local/lib/libgobject-2.0.so.0
#22 0x0000000804eb3695 in g_signal_emit_valist () from /usr/local/lib/libgobject-2.0.so.0
#23 0x0000000804eb3d84 in g_signal_emit () from /usr/local/lib/libgobject-2.0.so.0
#24 0x0000000804ea7b85 in g_weak_ref_get () from /usr/local/lib/libgobject-2.0.so.0
#25 0x0000000804ea36a9 in g_object_notify () from /usr/local/lib/libgobject-2.0.so.0
#26 0x000000080117ce3a in WebKit::FrameLoaderClient::dispatchDidCommitLoad () from /usr/local/lib/libwebkitgtk-3.0.so.0
#27 0x00000008015e7327 in WebCore::FrameLoader::receivedFirstData () from /usr/local/lib/libwebkitgtk-3.0.so.0
#28 0x00000008015e2faf in WebCore::DocumentWriter::setEncoding () from /usr/local/lib/libwebkitgtk-3.0.so.0
#29 0x00000008015ddb5f in WebCore::DocumentLoader::commitData () from /usr/local/lib/libwebkitgtk-3.0.so.0
#30 0x000000080117af49 in WebKit::FrameLoaderClient::committedLoad () from /usr/local/lib/libwebkitgtk-3.0.so.0
#31 0x00000008015dda6f in WebCore::DocumentLoader::commitLoad () from /usr/local/lib/libwebkitgtk-3.0.so.0
#32 0x000000080160e6a3 in WebCore::ResourceLoader::didReceiveData () from /usr/local/lib/libwebkitgtk-3.0.so.0
#33 0x000000080160842a in WebCore::MainResourceLoader::didReceiveData () from /usr/local/lib/libwebkitgtk-3.0.so.0
#34 0x0000000801607d24 in WebCore::MainResourceLoader::continueAfterContentPolicy () from /usr/local/lib/libwebkitgtk-3.0.so.0
#35 0x0000000801607f36 in WebCore::MainResourceLoader::continueAfterContentPolicy () from /usr/local/lib/libwebkitgtk-3.0.so.0
#36 0x000000080160b581 in WebCore::PolicyChecker::continueAfterContentPolicy () from /usr/local/lib/libwebkitgtk-3.0.so.0
#37 0x000000080117b8b9 in WebKit::FrameLoaderClient::dispatchDecidePolicyForResponse () from /usr/local/lib/libwebkitgtk-3.0.so.0
#38 0x0000000801608333 in WebCore::MainResourceLoader::didReceiveResponse () from /usr/local/lib/libwebkitgtk-3.0.so.0
#39 0x00000008016070c8 in WebCore::MainResourceLoader::handleDataLoadNow () from /usr/local/lib/libwebkitgtk-3.0.so.0
#40 0x000000080170a404 in WebCore::ThreadTimers::sharedTimerFiredInternal () from /usr/local/lib/libwebkitgtk-3.0.so.0
#41 0x0000000801ce3fb2 in WebCore::timeout_cb () from /usr/local/lib/libwebkitgtk-3.0.so.0
#42 0x000000080512a004 in g_list_sort_with_data () from /usr/local/lib/libglib-2.0.so.0
#43 0x000000080512d702 in g_main_context_dispatch () from /usr/local/lib/libglib-2.0.so.0
#44 0x000000080512daa3 in g_main_context_pending () from /usr/local/lib/libglib-2.0.so.0
#45 0x000000080512ddcf in g_main_loop_run () from /usr/local/lib/libglib-2.0.so.0
#46 0x000000080253e33a in gtk_main () from /usr/local/lib/libgtk-3.so.0
#47 0x0000000000446772 in main (argc=0x0, argv=0x7fffffffc6e8) at ../xombrero.c:8877

**Comment by marcopeereboom** [comment]
This is a webkit issue outside of xomrero's control
