### ISSUE TITLE
Do not load all tabs on start

### ISSUE THREAD

**Issue by abelbabel** [conformal/xombrero#71]
Hi,

this is a feature request.
I think that it might be a good idea to not load all tabs content on session start. A tab should be loaded when the user activates it for the first time. This will reduce load when starting xombrero with big sessions ...
I think firefox does it like I described.

Regards,
abelbabel

**Comment by marcopeereboom** [comment]
Sorry I disagree and functionality will therefore remain as is.  You can opt to not have tabs open so that you don't have to load them at start time.
