### ISSUE TITLE
bad fonts

### ISSUE THREAD

**Issue by abelbabel** [conformal/xombrero#72]
Hi,

I'm having bad fonts on many sites. They are blurred or too sharp.
I'm running *xombrero* under *FreeBSD 10.0*. It doesn't matter whether I compile it with *webkit-gtk2* or *webkit-gtk3*. It seems to not depend on the size of the font. Here on GitHub all fonts seem to be bad.

Regards,
abelbabel

**Comment by marcopeereboom** [comment]
Yes, some deps were not installed.

**Comment by onecan** [comment]
Fix for this issue can be found here:
https://wiki.archlinux.org/index.php/Dwb#Fuzzy_font_in_Github
