### ISSUE TITLE
Switch to XDG folders (.config, .local, .cache)

### ISSUE THREAD

**Issue by ChristianTacke** [conformal/xombrero#74]
Could you please switch to the official XDG directories?

So that config ends up in `~/.config/xombrero/`, data files are in `~/.local/share/xombrero` and cache data in `~/.cache/xombrero.

The appropiate glib functions are:
* [`g_get_user_config_dir()`](http://developer.gimp.org/api/2.0/glib/glib-Miscellaneous-Utility-Functions.html#g-get-user-config-dir)
* [`g_get_user_data_dir()`](http://developer.gimp.org/api/2.0/glib/glib-Miscellaneous-Utility-Functions.html#g-get-user-data-dir)
* [`g_get_user_cache_dir()`](http://developer.gimp.org/api/2.0/glib/glib-Miscellaneous-Utility-Functions.html#g-get-user-cache-dir)

Also possibly of interest, to get the downloads directory:
* [`GUserDirectory`](http://developer.gimp.org/api/2.0/glib/glib-Miscellaneous-Utility-Functions.html#GUserDirectory)

A simple migration plan:

1. If the XDG directories exist, use them.
2. If the old .xombrero exists, use it.
3. If none exist, use/create the XDG ones.

**Comment by marcopeereboom** [comment]
Sorry I will not do this.

**Comment by tukoz** [comment]
@ChristianTacke nicely put up :+1: Improve the workflow for XDG users (standards can do good) while changing nothing for non-XDG users (old way's always the best).
