### ISSUE TITLE
Read /etc/xombrero.conf

### ISSUE THREAD

**Issue by ChristianTacke** [conformal/xombrero#75]
As xombrero seems to follow "well established UNIX tradition": It's a tradition to read a configfile in `/etc/` before reading the user's configfile. So that the sysadmin can set useful defaults. Like the homepage, proxy, etc.

**Comment by marcopeereboom** [comment]
No one should be using xombrero on a shared machine with shared settings.  xombrero is meant to be slightly secure (it's a browser, I know) and this idea goes against that.
