### ISSUE TITLE
The Future Has Arrived

### ISSUE THREAD

**Issue by mitzip** [conformal/xombrero#76]
I just found xombrero and it is the PERFECT browser! I don't think I can praise you all enough for the work you've done in creating xombrero. Expect some BTC, as often as I can, and a dedicated fan/bug reporter/contributor. The only issue I have is, "Why haven't I heard about xombrero sooner!?" Feel free to close as "invalid", if you must. Though it could be considered an "enhancement". ;-)

**Comment by marcopeereboom** [comment]
Thanks.
