### ISSUE TITLE
color font statusbar

### ISSUE THREAD

**Issue by eins** [conformal/xombrero#79]
hi guys
i have archlinx 3.17.6-1-ARCH and xombrero-git 1.6.3.11.g0864f6c-1

and when i try to open a new url. i have white the bar status and the font to in white

i change /usr/share/xombrero/xombrero.css 
#statusbar > GtkEventBox 
{                                  
   background-image: 
   none;                                             
   background-color:
   black;
}

i try to find a color config in the man page but i can't find it
only font name and size
 
is any way i can change the font color for black ?
or the background for the search bar [ F9 ]

thanks

**Comment by clobkowicz** [comment]
I as well have this issue.
OpenBSD 5.7Beta
Version: 1.6.3
WebKit: 2.4.7
User Agent: 538.15
WebKit API: 3.0

As well, selecting text on a web page with the mouse, the highlight box is white with the highlighted text becoming white as well.

**Comment by TomCab** [comment]
Hi there

I have the same problem. My system is:

xombrero 1.6.3
Debian 8.0 (Jessie) amd64
installed from Debian package

Thanks

**Comment by keenerd** [comment]
This was fixed three weeks ago in f36afd122 and can be closed.

**Comment by jcvernaleo** [comment]
@keenerd Thanks for noticing.  I'll close the issue now.

**Comment by marcopeereboom** [comment]
This is not a fix!  The inverted colors are broken because of this.

**Comment by jcvernaleo** [comment]
This should be fixed in 2b755ffe5a672b97ca8a81f9230d8017a72f2cd0 (for real this time).
