### ISSUE TITLE
FS#316: Patch: tab_elems option for customizable tab components.

### ISSUE THREAD

**Issue by Walther-MD** [conformal/xombrero#8]
Originally a patch to support "enable_fav_icons: true" in the non-compact tabs, this patch was written to support a tab_elems option, which is a string of characters which determine what elements (and in what order) to display them in the tab:

T - tab title
C - close button
F - favicon/spinner
The default is "CT".

Patch for xombrero 1.6.3:
http://pastebin.com/WWXaDEfJ

**Comment by marcopeereboom** [comment]
That looks nice but I need a PR please.
