### ISSUE TITLE
Various usability issues

### ISSUE THREAD

**Issue by egassemcinatas** [conformal/xombrero#80]
This is a whishlish bug list about various usability issues to do with xombrero's laudable security features that make it something of a pain to use.

1) There is no indication of whether cookies or JavaScript are activated for the current domain.

This leaves the user to keep track manually by consulting the corresponding built-in pages showing cookie / js whitelists.  Opening is already a minor PITA:

2) After opening a new tab, the focus is in the URL line.  To facilitate opening built-in pages, focus could switch to the command (bottom) line automatically if the first character typed is a colon ":".

Checking the whitelists again gets you into the following trouble:

3) Reloading an internal ("about:") page is not possible and gets you an "Unable to load page" error.

4) The "Unable to load page" error page grabs keyboard focus in a way that makes it impossible to get anywhere useful with the Tab key or to enter a command until you click on the page with the mouse.

Sorry for the lengthy list, but this has a serious usability impact for someone who (like me) wants to enable trojan technologies only where necessary.  All was tested on linux, with version 1.6.3.

**Comment by marcopeereboom** [comment]
1) not entirely true, the || or > buttons give some sort of indication.  Most of the time || means no cookies AND no JS.
2) yes and i agree; i'll take a patch or open a separate issue for it
3) that is because of the replay protection (you want this or external parties could do things to your browser) and unfortunately can NOT be fixed/worked around without compromising security.
4) I am not able to reproduce this; i can enter commands etc.  If you still see this please open a separate issue with detailed steps and information about what webkit version and os version etc.

**Comment by egassemcinatas** [comment]
Thank you for your reply, and sorry to be so late with mine.

1) Thanks for mentioning this, I had wondered what that button did...  Could
this be added to the manual page?  In my experiments, the button switches and
indicates JavaScript support only (but that is the most important anyway).

2) Thank you!

3) I don't understand this; just because the user could reload "about:" pages,
external scripts should not have to be able to do anything more.  If this is a
Webkit restriction, of course you can't do anything about it.

4) I cannot reproduce it either right now, so I may have been mistaken.  Will
create a separate issue if it comes up again.

**Comment by marcopeereboom** [comment]
> 3) I don't understand this; just because the user could reload "about:" pages,
> external scripts should not have to be able to do anything more. If this is a
> Webkit restriction, of course you can't do anything about it.

An external site could link to these pages and there is nothing we could do about it.
So we have an anti replay mechanism in place to prevent bad things.  The unfortunate
side effect is that you can’t refresh about: pages.
