### ISSUE TITLE
FS#398 - Patch: toolbar enhancements: toggle command + auto-hide/unhide + paste to url

### ISSUE THREAD

**Issue by Walther-MD** [conformal/xombrero#9]
This patch adds some features to Xombrero:

1. It adds the "urltoggle" command, which allows users to show/hide the toolbar without affecting tab display (unlike "fullscreen").
2. It extends the commands "focusaddress" and "focussearch" to make the toolbar visible when invoked. Likewise, if the toolbar was made visible, upon hitting "Enter" (and start loading an url) the toolbar will be hidden again.
3. It supports middle-click pasting: when not middle-clicking a link, the selection gets pasted into the urlbar.

I can split this into patches if only some of the features are wanted.

Patch made against Xombrero-1.4.0 (but still applies to current version):

http://pastebin.com/EgM1wVMy

**Comment by marcopeereboom** [comment]
I think this is cool.  Can you please send a PR?
