### ISSUE TITLE
Text on address bar unreadable with dark gtk theme

### ISSUE THREAD

**Issue by akhilman** [conformal/xombrero#97]
Xombrero uses yellow background in addressbar if ssl enabled, but if theme sets text color to white text appears unreadable white on yellow.
As I can see all this colors defined in /usr/share/xombrero/xombrero.css, but seems I have no way to override it from home directory.
Please make xombrero read xombrero.css from ~/.xombrero/ direcotry or even better some css that will override parts of xombrero.css.

**Comment by marcopeereboom** [comment]
Should be fixed in current.
